export const en = {
  "appName": "LED Screen Manager",
  "appDescription": "Calculate specifications for your video wall setup.",
  "configuration": "Configuration",
  "cabinetResolution": "CABINET RESOLUTION",
  "widthPx": "Width (px)",
  "heightPx": "Height (px)",
  "cabinetPhysicalSize": "CABINET PHYSICAL SIZE",
  "widthCm": "Width (cm)",
  "heightCm": "Height (cm)",
  "screenLayout": "SCREEN LAYOUT",
  "cabinetsHorizontal": "Cabinets Horizontal",
  "cabinetsVertical": "Cabinets Vertical",
  "power": "POWER",
  "wattsPerCabinet": "Watts per Cabinet",
  "voltage": "Voltage",
  "novastarProcessor": "NOVASTAR PROCESSOR",
  "pixelsPerPort": "Pixels per Port",
  "pixelsPerPortHelper": "Enter a custom value or select a preset below.",
  "processorPresetDetails": "{capacity} pixels/port • {ports} ports total",
  "use": "Use",
  "costEstimation": "COST ESTIMATION (OPTIONAL)",
  "pricePerCabinet": "Price per Cabinet ($)",
  "pricePerProcessor": "Price per Processor ($)",
  "playerQuantity": "Player Quantity",
  "pricePerPlayer": "Price per Player ($)",
  "summary": "Summary",
  "totalResolution": "Total Resolution",
  "pixels": "pixels",
  "totalCabinets": "Total Cabinets",
  "cabinetsLayout": "{h} H x {v} V",
  "totalScreenSize": "Total Screen Size",
  "aspectRatio": "Aspect Ratio",
  "totalPowerDraw": "Total Power Draw",
  "amps": "Amps",
  "total15ABreakers": "Total 15A Breakers",
  "at80Capacity": "at 80% capacity",
  "total20ABreakers": "Total 20A Breakers",
  "totalNovastarPorts": "Total Novastar RJ45 Ports",
  "processorsNeeded": "Processors Needed",
  "customConfig": "Custom Config",
  "totalCabinetCost": "Total Cabinet Cost",
  "perCabinet": "/ cabinet",
  "totalProcessorCost": "Total Processor Cost",
  "totalPlayerCost": "Total Player Cost",
  "grandTotal": "Estimated Grand Total",
  "grandTotalSub": "Cabinets + Processors + Players",
  "cabinetsPer15ABreaker": "Cabinets per 15A Breaker",
  "cabinetsPer20ABreaker": "Cabinets per 20A Breaker",
  "cabinetsPerRJ45Port": "Cabinets per RJ45 Port",
  "maxPerPort": "max per port",
  "wiringDiagram": "Wiring Diagram",
  "data": "Data",
  "power20A": "Power (20A)",
  "wiringDiagramError": "Not enough information to generate a wiring diagram.",
  "wiringDiagramErrorHint": "Please ensure cabinet counts and power/port capacities are greater than zero.",
  "voltage120": "120V (North America)",
  "voltage208": "208V (North America)",
  "voltage240": "240V (Europe/Asia)",
  "proc_mctrl4k": "Novastar MCTRL4K",
  "proc_vx400": "Novastar VX400",
  "proc_vx600": "Novastar VX600",
  "proc_vx1000": "Novastar VX1000"
};
