export const en = {
  "appName": "LED Screen Manager",
  "appDescription": "Calculate specifications for your video wall setup.",
  "configuration": "Configuration",
  "cabinetResolution": "CABINET RESOLUTION",
  "widthPx": "Width (px)",
  "heightPx": "Height (px)",
  "cabinetPhysicalSize": "CABINET PHYSICAL SIZE",
  "widthCm": "Width (cm)",
  "heightCm": "Height (cm)",
  "screenLayout": "SCREEN LAYOUT",
  "cabinetsHorizontal": "Cabinets Horizontal",
  "cabinetsVertical": "Cabinets Vertical",
  "power": "POWER",
  "wattsPerCabinet": "Watts per Cabinet",
  "voltage": "Voltage",
  "novastarProcessor": "NOVASTAR PROCESSOR",
  "pixelsPerPort": "Pixels per Port",
  "pixelsPerPortHelper": "Enter a custom value or select a preset below.",
  "processorPresetDetailsWithInputs": "{capacity} pixels/port • {ports} ports • {inputs}",
  "use": "Use",
  "costEstimation": "COST ESTIMATION (OPTIONAL)",
  "pricePerCabinet": "Price per Cabinet ($)",
  "pricePerProcessor": "Price per Processor ($)",
  "playerQuantity": "Player Quantity",
  "pricePerPlayer": "Price per Player ($)",
  "summary": "Summary",
  "totalResolution": "Total Resolution",
  "pixels": "pixels",
  "totalCabinets": "Total Cabinets",
  "cabinetsLayout": "{h} H x {v} V",
  "totalScreenSize": "Total Screen Size",
  "aspectRatio": "Aspect Ratio",
  "totalPowerDraw": "Total Power Draw",
  "amps": "Amps",
  "at80Capacity": "at 80% capacity",
  "totalNovastarPorts": "Total Novastar RJ45 Ports",
  "processorsNeeded": "Processors Needed",
  "customConfig": "Custom Config",
  "totalCabinetCost": "Total Cabinet Cost",
  "perCabinet": "/ cabinet",
  "totalProcessorCost": "Total Processor Cost",
  "totalPlayerCost": "Total Player Cost",
  "grandTotal": "Estimated Grand Total",
  "grandTotalSub": "Cabinets + Processors + Players",
  "cabinetsPerRJ45Port": "Cabinets per RJ45 Port",
  "maxPerPort": "max per port",
  "wiringDiagram": "Wiring Diagram",
  "data": "Data",
  "wiringDiagramError": "Not enough information to generate a wiring diagram.",
  "wiringDiagramErrorHint": "Please ensure cabinet counts and power/port capacities are greater than zero.",
  "voltage120": "120V (North America)",
  "voltage208": "208V (North America)",
  "voltage240": "240V (Europe/Asia)",
  "voltage220_china": "220V 50Hz (China)",
  "proc_vx400": "Novastar VX400",
  "proc_vx600": "Novastar VX600",
  "proc_vx1000": "Novastar VX1000",
  "proc_vx16s": "Novastar VX16s",
  "proc_tb30": "Novastar TB30",
  "proc_tb40": "Novastar TB40",
  "proc_tb50": "Novastar TB50",
  "wiringOptions": "Wiring Options",
  "wiringPattern": "Wiring Pattern",
  "startCorner": "Start Corner",
  "vertical": "Vertical",
  "horizontal": "Horizontal",
  "totalBreakers": "Total {amps}A Breakers",
  "cabinetsPerBreaker": "Cabinets per {amps}A Breaker",
  "powerAmps": "Power ({amps}A)",
  "displayType": "DISPLAY TYPE",
  "synchronous": "Synchronous",
  "asynchronous": "Asynchronous",
  "inputs": "Inputs",
  "vxProSeries": "VX Pro Series",
  "tbSeries": "TB Series (Multimedia Players)",
  "print": "Print",
  "printSummary": "Print Summary",
  "screenSizeHelper": "SCREEN SIZE HELPER",
  "screenSizeHelperDescription": "Approximate a standard size based on cabinet dimensions. Result maintains a ~16:9 ratio.",
  "savePdf": "Save PDF",
  "paperSize": "Paper Size",
  "a4": "A4",
  "letter": "Letter",
  "dataWiringDiagram": "Data Wiring Diagram",
  "powerWiringDiagram": "Power Wiring Diagram",
  "diagramView": "Diagram View",
  "powerView": "Power"
};