export const zh = {
  "appName": "LED屏幕管理器",
  "appDescription": "为您的视频墙设置计算规格。",
  "configuration": "配置",
  "cabinetResolution": "箱体分辨率",
  "widthPx": "宽度 (像素)",
  "heightPx": "高度 (像素)",
  "cabinetPhysicalSize": "箱体物理尺寸",
  "widthCm": "宽度 (厘米)",
  "heightCm": "高度 (厘米)",
  "screenLayout": "屏幕布局",
  "cabinetsHorizontal": "水平箱体数",
  "cabinetsVertical": "垂直箱体数",
  "power": "电源",
  "wattsPerCabinet": "每箱体功率 (瓦)",
  "voltage": "电压",
  "novastarProcessor": "诺瓦星云处理器",
  "pixelsPerPort": "每端口像素",
  "pixelsPerPortHelper": "输入自定义值或选择下面的预设。",
  "processorPresetDetailsWithInputs": "{capacity} 像素/端口 • {ports} 端口 • {inputs}",
  "use": "使用",
  "costEstimation": "成本估算 (可选)",
  "pricePerCabinet": "每箱体价格 ($)",
  "pricePerProcessor": "每处理器价格 ($)",
  "playerQuantity": "播放器数量",
  "pricePerPlayer": "每播放器价格 ($)",
  "summary": "摘要",
  "totalResolution": "总分辨率",
  "pixels": "像素",
  "totalCabinets": "总箱体数",
  "cabinets": "箱体",
  "cabinetsLayout": "{h} 水平 x {v} 垂直",
  "totalScreenSize": "总屏幕尺寸",
  "aspectRatio": "宽高比",
  "totalPowerDraw": "总功耗",
  "amps": "安培",
  "at80Capacity": "在 80% 容量下",
  "totalNovastarPorts": "总诺瓦星云 RJ45 端口",
  "processorsNeeded": "所需处理器",
  "customConfig": "自定义配置",
  "totalCabinetCost": "总箱体成本",
  "perCabinet": "/ 箱体",
  "totalProcessorCost": "总处理器成本",
  "totalPlayerCost": "总播放器成本",
  "grandTotal": "预计总成本",
  "grandTotalSub": "箱体 + 处理器 + 播放器",
  "cabinetsPerRJ45Port": "每 RJ45 端口箱体数",
  "maxPerPort": "每端口最大值",
  "wiringDiagram": "接线图",
  "data": "数据",
  "wiringDiagramError": "信息不足，无法生成接线图。",
  "wiringDiagramErrorHint": "请确保箱体数量和电源/端口容量大于零。",
  "voltage120": "120V (北美)",
  "voltage208": "208V (北美)",
  "voltage240": "240V (欧洲/亚洲)",
  "voltage220_china": "220V 50Hz (中国)",
  "proc_vx400": "诺瓦星云 VX400",
  "proc_vx600": "诺瓦星云 VX600",
  "proc_vx1000": "诺瓦星云 VX1000",
  "proc_vx16s": "诺瓦星云 VX16s",
  "proc_tb30": "诺瓦星云 TB30",
  "proc_tb40": "诺瓦星云 TB40",
  "proc_tb50": "诺瓦星云 TB50",
  "wiringOptions": "接线选项",
  "wiringPattern": "接线模式",
  "startCorner": "起始角落",
  "vertical": "垂直",
  "horizontal": "水平",
  "totalBreakers": "总 {amps}A 断路器",
  "cabinetsPerBreaker": "每 {amps}A 断路器箱体数",
  "powerAmps": "电源 ({amps}A)",
  "displayType": "显示类型",
  "synchronous": "同步",
  "asynchronous": "异步",
  "inputs": "输入接口",
  "vxProSeries": "VX Pro 系列",
  "tbSeries": "TB 系列 (多媒体播放器)",
  "print": "打印",
  "printSummary": "打印摘要",
  "screenSizeHelper": "屏幕尺寸助手",
  "screenSizeHelperDescription": "根据箱体尺寸估算标准屏幕尺寸。结果将保持约16:9的比例。",
  "savePdf": "保存PDF",
  "paperSize": "纸张尺寸",
  "a4": "A4",
  "letter": "Letter",
  "dataWiringDiagram": "数据接线图",
  "powerWiringDiagram": "电源接线图",
  "diagramView": "图表视图",
  "powerView": "电源",
  "wiringMode": "接线模式",
  "autoMode": "自动",
  "manualMode": "手动",
  "selectPathToDraw": "选择一个电路/端口以开始绘制路径。",
  "clearAllPaths": "清除所有路径",
  "pathCapacity": "{count}/{limit}",
  "pathComplete": "已满",
  "addPort": "添加端口",
  "addCircuit": "添加电路",
  "diagramTooLargeError": "图表太大无法渲染",
  "diagramTooLargeErrorHint": "由于性能限制，无法为超过 {limit} 个箱体的屏幕显示接线图。"
};